### ISSUE TITLE
Aktarma gerçekleşmiyor

### ISSUE THREAD

**Issue by emresaracoglu** [aozisik/php-csv-importer#1]
Merhaba,

Yazılımınız için teşekkür ederim ancak tüm bilgiler doğru olmasina rağmen maalesef CSV dosyasini ilgili veritabanina aktarmasinda sorun yaşıyorum.

> Processing...
> SQL dosyaları veritabanına aktarılıyor.

Herhangi bir hata oluşmadan, bu şekilde kalmaktaidr. Bu konuda yardımcı olabilir misiniz?

**Comment by aozisik** [comment]
Merhaba Emre Bey,

Ben bu scripti Php'yi ilk öğrendiğimde yazmıştım. Berbat bir script maalesef :) Yine de belki ihtiyacınız vardır, kullanmanız gerekiyordur diye düşünerek ufak tefek bir iki fix yolladım. Son halini çekip deneyebilir misiniz? Çalışmazsa tekrardan bakalım error.txt'de çıkan hatalara göre.

Not: Kontrolü direkt olarak veritabanından yapın. Arayüz doğru çalışmasa bile veriyi import edebilir arkaplanda.

İyi çalışmalar :)

**Comment by emresaracoglu** [comment]
Merhaba,

Aslında çalışmanızı yeniden düzenleyeceğinizi tahmin etmiyordum ve bu ilginiz beni oldukça şaşırttı, bunun için tekrar teşekkür ederim. :)
Mesajınızdan sonra hemen test etmek istedim ve arayüz öncekinden daha stabil olduğunu söyleyebilirim ancak import etme işlemi maalesef başarılı sonuclanmiyor. İnanin birçok kez test ettim farklı veritabanlari ile ama sonucu değiştiremedim.

İşleme dair ekran resmi ise: 
![cvsimport](https://cloud.githubusercontent.com/assets/297968/24982273/5c43672a-1fe9-11e7-9f10-a22bee25d826.png)

**Comment by emresaracoglu** [comment]
Az önce farrkettim, bazi CVS dosyalari nedenini anlamadiğim şekilde import etme işlemini gerçekleştirmiyor, bazilarini ise gerçekleştiriyor. 
Eğer müsait bir zamaninizda bu durumu giderebilirseniz çok sevinirim, ayrica oluşturmuş oluduğu "_Columns_" CVS içeriğiden değilde, otomatik olarak `COL 1`, `COL 2` olarak oluşturabilir mi?

![importcvs](https://cloud.githubusercontent.com/assets/297968/25001222/27f29e1e-204d-11e7-9439-20e080768e26.png)

Bunu rica etmemin sebebi ise; eklenmesi gereken içeriğin, column olarak eklenmesi. Bunun yerine `COL <sayi>` oluşturmasi daha iyi olabilir düşüncesindeyim.

**Comment by aozisik** [comment]
Bazı CSV dosyalarının içerisindeki seperator ve enclosing karakterleri farklı olabilir. Yani bazı dosyalar , karakteri ile ayırırken bazıları da ; karakteri ile ayırabiliyor fieldları. Hatta bazen tab karakteri (\t) ile de ayrılmış olabiliyor. Dosyayı bir text editör ile açarak hangi değerle ayrıldığını bulabilirsiniz. Bu değeri seperator alanına girmeniz gerek.

Aynı şekilde bazen fieldların etrafında " veya ' olabiliyor ya da hiç tırnak işareti bulunmayabiliyor. Buna göre de enclosing karakterini belirlemelisiniz.

Bunlar sorununuzu çözmediyse, çalışmayan CSV dosyasını veya hata mesajlarını görmeden sorunu çözemeyiz. Dediğim gibi, işlem gerçekleşmediğinde error.txt içerisine hata mesajlarını yazması lazım.

Column isimlerini için de bu değişikliği kendiniz yapabilirsiniz. Bu script ilk satırın field isimlerini içeren bir header satırı olacağını varsaymış. process.php içerisinde 29. satırdaki kodu değiştirerek istediğiniz patternda column ismi vermesini sağlayabilirsiniz.

**Comment by emresaracoglu** [comment]
Belirtmiş olduğunuz satırı;
`$table_columns[] = '`COL `' . ' varchar(255) NOT NULL';`
şeklinde düzenledim, tüm kolon isimlerine `COL ` ismini verdiği için elbette tablo oluşturma esnasinda hata oluştu. 
Hata kaydinda ise;
```
CREATE TABLE IF NOT EXISTS csv_data1(`COL` varchar(255) NOT NULL,`COL` varchar(255) NOT NULL,`COL` varchar(255) NOT NULL,`COL` varchar(255) NOT NULL,`COL` varchar(255) NOT NULL,`COL` varchar(255) NOT NULL,`COL` varchar(255) NOT NULL) ENGINE=MyISAM DEFAULT CHARSET=utf8;
42S21, 1060, Duplicate column name 'COL'
```

ben de böyle bir method ile çözebileceğimi düşündüm ancak değişen bir durum olmadi.

```
foreach($table_header_array as $column) {
    for ($c=0; $c < $column; $c++) {
         $table_columns[] = '`' . $column . '`' . ' varchar(255) NOT NULL';
   }
}
```

**Comment by aozisik** [comment]
Böyle deneyebilir misiniz?

    foreach($table_header_array as $index => $column) {
       $table_columns[] = '`COL' . ($index + 1) . '` varchar(255) NOT NULL';
    }

**Comment by emresaracoglu** [comment]
Daha önce süper bir insan olduğunuzu söylemiş miydim? :) 
Sorunsuzca çalışıyor, **teşekkür ederim.**

**Comment by aozisik** [comment]
Önemli değil :) İyi çalışmalar!
